import React from 'react';
import './ExecutiveReportModal.css';
import { useNotification } from '../NotificationContext';

const ExecutiveReportModal = ({ isOpen, onClose, type = 'adr', data = {} }) => {
  const { showSuccess } = useNotification();

  if (!isOpen) return null;

  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    let mdContent = '';
    let filename = '';

    if (type === 'adr') {
      filename = `ADR-001-${(data.recommendedArchitecture || 'Architecture').replace(/\s+/g, '-')}.md`;
      mdContent = `# Architecture Decision Record (ADR-001)
**Title:** Adoption of ${data.recommendedArchitecture || 'Target System Pattern'}  
**Status:** APPROVED / ACCEPTED  
**Date:** ${today}  
**Confidence Score:** ${data.confidenceScore || 95}%  

## Executive Summary
${data.summary || 'Architecture synthesis completed based on domain complexity and team scale.'}

## Key Benefits
${(data.keyBenefits || []).map(b => `- ${b}`).join('\n')}

## Engineering Trade-offs & Risks
${(data.architecturalTradeOffs || []).map(t => `- ${t}`).join('\n')}

## Recommended Technology Stack
| Architecture Layer | Technology Selection |
| --- | --- |
${Object.entries(data.suggestedTechStack || {}).map(([layer, tech]) => `| ${layer} | ${tech} |`).join('\n')}

## Implementation Guidelines
${(data.implementationGuidelines || []).map(g => `1. ${g}`).join('\n')}

---
*Generated by Synaptech: An AI-Driven Architecture and Agile Intelligence Platform*
`;
    } else {
      filename = `Sprint-Executive-Briefing-${today.replace(/\s+/g, '-')}.md`;
      mdContent = `# Sprint & Project Health Executive Briefing
**Date:** ${today}  
**Platform:** Synaptech Agile Intelligence Core  

## Telemetry Metrics
- **Sprint Velocity:** ${data.sprintVelocity || 35} story points
- **Bug Trend:** ${(data.bugTrend || 'Stable').toUpperCase()}
- **Technical Debt Index:** ${(data.technicalDebt || 'Moderate').toUpperCase()}
- **Code Quality Score:** ${data.codeQualityIndex || 75}/100

## AI Simulation & Risk Recommendations
${(data.recommendations || [
  'Allocate 20% sprint bandwidth to technical debt refactoring.',
  'Enforce Definition of Ready on upstream requirements to stabilize velocity.',
  'Implement automated contract testing in CI pipeline.'
]).map(r => `- ${r}`).join('\n')}

---
*Generated by Synaptech: An AI-Driven Architecture and Agile Intelligence Platform*
`;
    }

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showSuccess(`Report downloaded: ${filename}`);
  };

  return (
    <div className="report-modal-backdrop">
      <div className="report-modal-content">
        {/* Header Controls */}
        <div className="report-modal-header">
          <h3>
            {type === 'adr' ? '📄 Architecture Decision Record (ADR)' : '📊 Sprint Executive Briefing'}
          </h3>
          <div className="report-modal-actions">
            <button
              type="button"
              onClick={handleDownloadMarkdown}
              style={{
                background: 'rgba(255, 255, 255, 0.1)',
                color: '#fff',
                border: '1px solid rgba(255, 255, 255, 0.2)',
                padding: '6px 14px',
                borderRadius: '6px',
                cursor: 'pointer',
                fontWeight: 600,
                fontSize: '0.85rem'
              }}
            >
              💾 Download .MD
            </button>
            <button
              type="button"
              onClick={handlePrint}
              style={{
                background: 'var(--brand-primary)',
                color: '#fff',
                border: 'none',
                padding: '6px 16px',
                borderRadius: '6px',
                cursor: 'pointer',
                fontWeight: 600,
                fontSize: '0.85rem'
              }}
            >
              🖨️ Print / Save PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              style={{
                background: 'transparent',
                color: '#94a3b8',
                border: 'none',
                fontSize: '1.2rem',
                cursor: 'pointer',
                marginLeft: '8px'
              }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* Printable Executive Document Body */}
        <div className="report-scroll-body">
          <div className="executive-doc">
            {/* Brand Header */}
            <div className="doc-brand-bar">
              <div>
                <div className="doc-brand-title">SYNAPTECH</div>
                <div style={{ fontSize: '0.75rem', color: '#64748b' }}>
                  AI-Driven Architecture &amp; Agile Intelligence Platform
                </div>
              </div>
              <div className="doc-brand-meta">
                <div><strong>Classification:</strong> Official Internal Record</div>
                <div><strong>Date:</strong> {today}</div>
              </div>
            </div>

            {/* Document Details based on Type */}
            {type === 'adr' ? (
              <>
                <div className="doc-title-section">
                  <h1>ADR-001: Adoption of {data.recommendedArchitecture || 'Clean Architecture'}</h1>
                  <span className="doc-status-badge">Status: Approved &bull; Confidence {data.confidenceScore || 95}%</span>
                </div>

                <div className="doc-section">
                  <h3>1. Context &amp; Decision Drivers</h3>
                  <p>{data.summary || 'Architecture synthesis performed based on domain requirements, operational budget, and engineering team size.'}</p>
                </div>

                <div className="doc-section">
                  <h3>2. Architectural Strengths &amp; Benefits</h3>
                  <ul>
                    {(data.keyBenefits || [
                      'Decoupled domain boundaries with high developer velocity.',
                      'Isolated failure blast radius and resilience under burst load.',
                      'Linear scalability across cloud-managed environments.'
                    ]).map((b, i) => (
                      <li key={i}>{b}</li>
                    ))}
                  </ul>
                </div>

                <div className="doc-section">
                  <h3>3. Engineering Trade-offs &amp; Mitigations</h3>
                  <ul>
                    {(data.architecturalTradeOffs || [
                      'Increased observability overhead across distributed traces.',
                      'Requires adherence to strict bounded contexts.'
                    ]).map((t, i) => (
                      <li key={i}>{t}</li>
                    ))}
                  </ul>
                </div>

                {data.suggestedTechStack && Object.keys(data.suggestedTechStack).length > 0 && (
                  <div className="doc-section">
                    <h3>4. Technology Stack Blueprint</h3>
                    <table className="doc-table">
                      <thead>
                        <tr>
                          <th>Architecture Layer</th>
                          <th>Selected Technology / Tooling</th>
                        </tr>
                      </thead>
                      <tbody>
                        {Object.entries(data.suggestedTechStack).map(([layer, tech]) => (
                          <tr key={layer}>
                            <td><strong>{layer}</strong></td>
                            <td>{tech}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {data.implementationGuidelines && data.implementationGuidelines.length > 0 && (
                  <div className="doc-section">
                    <h3>5. Key Implementation Guidelines</h3>
                    <ol>
                      {data.implementationGuidelines.map((g, i) => (
                        <li key={i}>{g}</li>
                      ))}
                    </ol>
                  </div>
                )}
              </>
            ) : (
              <>
                <div className="doc-title-section">
                  <h1>Sprint &amp; Project Health Executive Briefing</h1>
                  <span className="doc-status-badge">Status: Telemetry Synced</span>
                </div>

                <div className="doc-section">
                  <h3>1. Active Telemetry Overview</h3>
                  <table className="doc-table">
                    <thead>
                      <tr>
                        <th>Metric</th>
                        <th>Current Value</th>
                        <th>Health Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td><strong>Sprint Velocity</strong></td>
                        <td>{data.sprintVelocity || 35} pts</td>
                        <td>Normal Band</td>
                      </tr>
                      <tr>
                        <td><strong>Bug Trend</strong></td>
                        <td>{(data.bugTrend || 'Stable').toUpperCase()}</td>
                        <td>Monitored</td>
                      </tr>
                      <tr>
                        <td><strong>Technical Debt</strong></td>
                        <td>{(data.technicalDebt || 'Moderate').toUpperCase()}</td>
                        <td>Manageable</td>
                      </tr>
                      <tr>
                        <td><strong>Code Quality Index</strong></td>
                        <td>{data.codeQualityIndex || 75} / 100</td>
                        <td>Optimal</td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                <div className="doc-section">
                  <h3>2. Strategic Engineering Recommendations</h3>
                  <ul>
                    {(data.recommendations || [
                      'Maintain 80/20 capacity allocation to avoid debt accumulation.',
                      'Implement automated static analysis in pull request gates.',
                      'Enforce Definition of Ready for all upcoming sprint candidate items.'
                    ]).map((rec, i) => (
                      <li key={i}>{rec}</li>
                    ))}
                  </ul>
                </div>
              </>
            )}

            {/* Signatories & Approvers */}
            <div className="doc-signatories">
              <div className="sign-block">
                <div className="sign-line" />
                <div className="sign-label">Lead Software Architect</div>
              </div>
              <div className="sign-block">
                <div className="sign-line" />
                <div className="sign-label">VP of Engineering / Product Owner</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExecutiveReportModal;
