-- V2__requirements.sql
-- Synaptech AI Platform: Semantic Requirement Intelligence Schema

CREATE TABLE IF NOT EXISTS requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    project_id BIGINT NOT NULL,
    req_code VARCHAR(50) NOT NULL,
    title VARCHAR(255),
    description TEXT NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'FUNCTIONAL',
    ambiguity_score DOUBLE PRECISION DEFAULT 0.0,
    quality_score DOUBLE PRECISION DEFAULT 1.0,
    quality_status VARCHAR(50) DEFAULT 'APPROVED',
    embedding_reference VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_requirements_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_req_project ON requirements(project_id);
CREATE INDEX IF NOT EXISTS idx_req_code ON requirements(project_id, req_code);
CREATE INDEX IF NOT EXISTS idx_req_category ON requirements(category);

-- Seed realistic requirements for the demo project
INSERT INTO requirements (project_id, req_code, title, description, category, ambiguity_score, quality_score, quality_status)
SELECT 1, 'REQ-001', 'User Authentication and Authorization', 'The system shall authenticate users using JWT with BCrypt password hashing and enforce role-based access control.', 'SECURITY', 0.08, 0.92, 'APPROVED'
WHERE NOT EXISTS (SELECT 1 FROM requirements WHERE req_code = 'REQ-001');

INSERT INTO requirements (project_id, req_code, title, description, category, ambiguity_score, quality_score, quality_status)
SELECT 1, 'REQ-002', 'High-Throughput Telemetry Ingestion', 'The platform must be fast, scalable, and support concurrent telemetry streams with response time under 150ms.', 'PERFORMANCE', 0.42, 0.58, 'NEEDS_REVISION'
WHERE NOT EXISTS (SELECT 1 FROM requirements WHERE req_code = 'REQ-002');

INSERT INTO requirements (project_id, req_code, title, description, category, ambiguity_score, quality_score, quality_status)
SELECT 1, 'REQ-003', 'Automated What-If Risk Simulation', 'The system shall execute isolated scenario perturbations on project telemetry without altering the live production baseline.', 'FUNCTIONAL', 0.12, 0.88, 'APPROVED'
WHERE NOT EXISTS (SELECT 1 FROM requirements WHERE req_code = 'REQ-003');
