-- V3__agile_artifacts.sql
-- Synaptech AI Platform: Agile Delivery & Backlog Artifacts Schema

CREATE TABLE IF NOT EXISTS user_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    project_id BIGINT NOT NULL,
    requirement_id BIGINT,
    story_code VARCHAR(50),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    story_points INTEGER DEFAULT 3,
    priority VARCHAR(20) DEFAULT 'MEDIUM',
    status VARCHAR(50) DEFAULT 'BACKLOG',
    sprint_number INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_stories_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_stories_req FOREIGN KEY (requirement_id) REFERENCES requirements(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_story_project ON user_stories(project_id);
CREATE INDEX IF NOT EXISTS idx_story_sprint ON user_stories(project_id, sprint_number);
CREATE INDEX IF NOT EXISTS idx_story_status ON user_stories(status);

-- Seed Baseline Stories
INSERT INTO user_stories (project_id, story_code, title, description, story_points, priority, status, sprint_number)
SELECT 1, 'US-001', 'Implement JWT Filter and Security Chain', 'Secure REST endpoints with JJWT and stateless session creation policy.', 5, 'HIGH', 'COMPLETED', 1
WHERE NOT EXISTS (SELECT 1 FROM user_stories WHERE story_code = 'US-001');

INSERT INTO user_stories (project_id, story_code, title, description, story_points, priority, status, sprint_number)
SELECT 1, 'US-002', 'Deploy FastAPI Microservice and LightGBM Inference', 'Expose /api/ai/risk/predict and TreeSHAP attribution endpoints.', 8, 'CRITICAL', 'IN_PROGRESS', 2
WHERE NOT EXISTS (SELECT 1 FROM user_stories WHERE story_code = 'US-002');
