-- V4__architecture_code.sql
-- Synaptech AI Platform: Architecture Decisions & Static Code Telemetry Schema

CREATE TABLE IF NOT EXISTS architecture_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    project_id BIGINT NOT NULL,
    component_name VARCHAR(100) NOT NULL,
    component_type VARCHAR(50) DEFAULT 'Service',
    layer VARCHAR(50) DEFAULT 'DOMAIN',
    technology_stack VARCHAR(100) DEFAULT 'Java/Spring Boot',
    failure_criticality DOUBLE PRECISION DEFAULT 0.5,
    description TEXT,
    quality_attributes TEXT,
    criticality VARCHAR(20) DEFAULT 'MEDIUM',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_arch_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_arch_project ON architecture_components(project_id);

CREATE TABLE IF NOT EXISTS code_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    project_id BIGINT NOT NULL,
    architecture_component_id BIGINT,
    module_name VARCHAR(100),
    module_path VARCHAR(255) NOT NULL,
    file_path VARCHAR(255),
    loc INTEGER DEFAULT 0,
    cyclomatic_complexity DOUBLE PRECISION DEFAULT 1.0,
    halstead_volume DOUBLE PRECISION DEFAULT 0.0,
    technical_debt_hours DOUBLE PRECISION DEFAULT 0.0,
    code_quality_index DOUBLE PRECISION DEFAULT 100.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_code_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE,
    CONSTRAINT fk_code_arch FOREIGN KEY (architecture_component_id) REFERENCES architecture_components(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_code_project ON code_modules(project_id);
CREATE INDEX IF NOT EXISTS idx_code_arch ON code_modules(architecture_component_id);

-- Seed Baseline Architecture & Code Artifacts
INSERT INTO architecture_components (project_id, component_name, component_type, layer, technology_stack, failure_criticality, description, quality_attributes, criticality)
SELECT 1, 'Spring Boot API Gateway', 'Service Gateway', 'PRESENTATION', 'Java/Spring Boot', 0.85, 'REST API entrypoint with Spring Security filter chain and CORS configuration', 'Security, High Availability', 'CRITICAL'
WHERE NOT EXISTS (SELECT 1 FROM architecture_components WHERE component_name = 'Spring Boot API Gateway');

INSERT INTO architecture_components (project_id, component_name, component_type, layer, technology_stack, failure_criticality, description, quality_attributes, criticality)
SELECT 1, 'Python AI Inference Microservice', 'Compute Service', 'INTEGRATION', 'Python/FastAPI', 0.80, 'FastAPI microservice executing LightGBM risk regression and TreeSHAP attribution', 'Low Latency, High Precision', 'HIGH'
WHERE NOT EXISTS (SELECT 1 FROM architecture_components WHERE component_name = 'Python AI Inference Microservice');

INSERT INTO code_modules (project_id, architecture_component_id, module_name, module_path, file_path, loc, cyclomatic_complexity, halstead_volume, technical_debt_hours, code_quality_index)
SELECT 1, 1, 'SecurityConfig.java', 'src/main/java/com/snaptech/backend/security/SecurityConfig.java', 'src/main/java/com/snaptech/backend/security/SecurityConfig.java', 71, 4.0, 385.2, 2.5, 92.0
WHERE NOT EXISTS (SELECT 1 FROM code_modules WHERE module_name = 'SecurityConfig.java' OR module_path = 'src/main/java/com/snaptech/backend/security/SecurityConfig.java');

INSERT INTO code_modules (project_id, architecture_component_id, module_name, module_path, file_path, loc, cyclomatic_complexity, halstead_volume, technical_debt_hours, code_quality_index)
SELECT 1, 2, 'app.py', 'ai-services/app.py', 'ai-services/app.py', 704, 18.0, 1420.5, 8.0, 85.0
WHERE NOT EXISTS (SELECT 1 FROM code_modules WHERE module_name = 'app.py' OR module_path = 'ai-services/app.py');
