-- V6__traceability.sql
-- Synaptech AI Platform: Artifact Traceability & Dependency Graph Schema

CREATE TABLE IF NOT EXISTS traceability_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    project_id BIGINT NOT NULL,
    source_artifact_id BIGINT NOT NULL,
    source_artifact_type VARCHAR(50) NOT NULL,
    source_artifact_code VARCHAR(50),
    target_artifact_id BIGINT NOT NULL,
    target_artifact_type VARCHAR(50) NOT NULL,
    target_artifact_code VARCHAR(50),
    link_type VARCHAR(50) NOT NULL DEFAULT 'IMPLEMENTS',
    weight DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_link_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_link_source ON traceability_links(project_id, source_artifact_id, source_artifact_type);
CREATE INDEX IF NOT EXISTS idx_link_target ON traceability_links(project_id, target_artifact_id, target_artifact_type);
CREATE INDEX IF NOT EXISTS idx_link_type ON traceability_links(link_type);

-- Seed Baseline Traceability Chain: REQ -> US -> ARCH -> CODE
INSERT INTO traceability_links (project_id, source_artifact_id, source_artifact_type, source_artifact_code, target_artifact_id, target_artifact_type, target_artifact_code, link_type, weight)
SELECT 1, 1, 'REQUIREMENT', 'REQ-001', 1, 'USER_STORY', 'US-001', 'REFINES', 1.0
WHERE NOT EXISTS (SELECT 1 FROM traceability_links WHERE source_artifact_code = 'REQ-001' AND target_artifact_code = 'US-001');

INSERT INTO traceability_links (project_id, source_artifact_id, source_artifact_type, source_artifact_code, target_artifact_id, target_artifact_type, target_artifact_code, link_type, weight)
SELECT 1, 1, 'USER_STORY', 'US-001', 1, 'ARCH_COMPONENT', 'ARCH-001', 'ARCHITECTED_AS', 0.90
WHERE NOT EXISTS (SELECT 1 FROM traceability_links WHERE source_artifact_code = 'US-001' AND target_artifact_code = 'ARCH-001');

INSERT INTO traceability_links (project_id, source_artifact_id, source_artifact_type, source_artifact_code, target_artifact_id, target_artifact_type, target_artifact_code, link_type, weight)
SELECT 1, 1, 'ARCH_COMPONENT', 'ARCH-001', 1, 'CODE_MODULE', 'CODE-001', 'IMPLEMENTED_BY', 0.85
WHERE NOT EXISTS (SELECT 1 FROM traceability_links WHERE source_artifact_code = 'ARCH-001' AND target_artifact_code = 'CODE-001');
