-- V7__simulations.sql
-- Synaptech AI Platform: Isolated What-If Counterfactual Simulations Schema

CREATE TABLE IF NOT EXISTS change_simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    project_id BIGINT NOT NULL,
    scenario_name VARCHAR(255) NOT NULL,
    mutation_payload TEXT NOT NULL,
    baseline_risk DOUBLE PRECISION DEFAULT 0.0,
    simulated_risk DOUBLE PRECISION DEFAULT 0.0,
    delta_risk DOUBLE PRECISION DEFAULT 0.0,
    impacted_artifact_count INTEGER DEFAULT 0,
    impacted_artifacts_json TEXT,
    top_drivers_json TEXT,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sim_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sim_project_time ON change_simulations(project_id, executed_at DESC);

-- Seed Baseline Scenario Simulation
INSERT INTO change_simulations (project_id, scenario_name, mutation_payload, baseline_risk, simulated_risk, delta_risk, impacted_artifact_count, top_drivers_json)
SELECT 1, 'Technical Debt Surge Scenario', '{"technical_debt_ratio": 0.45, "sprint_velocity_variance": 0.35}', 28.0, 52.5, 24.5, 3, '[{"feature":"technical_debt_ratio","shap_delta":3.8},{"feature":"sprint_velocity_variance","shap_delta":2.4}]'
WHERE NOT EXISTS (SELECT 1 FROM change_simulations WHERE project_id = 1 AND scenario_name = 'Technical Debt Surge Scenario');
